### ISSUE TITLE
Bug 🐞 found in mobile breakpoints

### ISSUE THREAD

**Issue by brentschneider** [18F/join.tts.gsa.gov#134]
Issue occurs between breakpoint 341px – 370px the page layout breaks, effects  `<main id="main-content">` content block.

- Observed on mobile (iPhone 6s) 
- Reproduced using the web inspector in FireFox and Chrome.

Screenshots:

**Impacts content area in orange.**
<img width="371" alt="content-area" src="https://user-images.githubusercontent.com/744669/42831987-ba49a444-89a4-11e8-8078-577f47f8beb0.png">

Breakpoint: 342
<img width="404" alt="342 width breakpoint" src="https://user-images.githubusercontent.com/744669/42831989-ba746ca6-89a4-11e8-8c64-a15a2e65e7ea.png">

Breakpoint: 369
<img width="402" alt="369 width breakpoint" src="https://user-images.githubusercontent.com/744669/42831988-ba60926c-89a4-11e8-8d23-e9a3c11cba82.png">

**Comment by awfrancisco** [comment]
This seems pretty similar to #109. They should be investigated together.

**Comment by maya** [comment]
@awfrancisco I figured this one out. It's actually the title bar that's pushing it down and making it appear this way.

This is what it looks like right before it breaks:
<img width="442" alt="screen shot 2019-01-14 at 11 32 55 am" src="https://user-images.githubusercontent.com/5249443/51135969-32992d00-17f0-11e9-98fe-f01b574005c5.png">

This is what it looks like after it breaks when I changed the text to black. Since it is white usually, you can't see it. And it looks like it's trying to fit the space with the title and main nav content.

<img width="463" alt="screen shot 2019-01-14 at 11 33 07 am" src="https://user-images.githubusercontent.com/5249443/51136005-4a70b100-17f0-11e9-915a-897c25e5f6d1.png">

To fix this you could hide the logo text at smaller screen sizes or come up with a shorter text at small screen sizes.

**Comment by maya** [comment]
Fixed in #179. Thanks for reporting it 👍
